CREATE USER app WITH PASSWORD 'ua95qI0eTN^Y8@99a8@a5pF3Tyw96';
GRANT CONNECT ON DATABASE aeroclub TO app;
GRANT ALL PRIVILEGES ON DATABASE aeroclub TO app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO app;

